// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	categorysvc "github.com/cp25sy5-modjot/main-service/internal/category/service"
	entity "github.com/cp25sy5-modjot/main-service/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: userId, input
func (_m *MockService) Create(userId string, input *categorysvc.CategoryCreateInput) (*entity.Category, error) {
	ret := _m.Called(userId, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *categorysvc.CategoryCreateInput) (*entity.Category, error)); ok {
		return rf(userId, input)
	}
	if rf, ok := ret.Get(0).(func(string, *categorysvc.CategoryCreateInput) *entity.Category); ok {
		r0 = rf(userId, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *categorysvc.CategoryCreateInput) error); ok {
		r1 = rf(userId, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userId string
//   - input *categorysvc.CategoryCreateInput
func (_e *MockService_Expecter) Create(userId interface{}, input interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", userId, input)}
}

func (_c *MockService_Create_Call) Run(run func(userId string, input *categorysvc.CategoryCreateInput)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*categorysvc.CategoryCreateInput))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *entity.Category, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(string, *categorysvc.CategoryCreateInput) (*entity.Category, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDefaultCategories provides a mock function with given fields: userID
func (_m *MockService) CreateDefaultCategories(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateDefaultCategories")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CreateDefaultCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDefaultCategories'
type MockService_CreateDefaultCategories_Call struct {
	*mock.Call
}

// CreateDefaultCategories is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) CreateDefaultCategories(userID interface{}) *MockService_CreateDefaultCategories_Call {
	return &MockService_CreateDefaultCategories_Call{Call: _e.mock.On("CreateDefaultCategories", userID)}
}

func (_c *MockService_CreateDefaultCategories_Call) Run(run func(userID string)) *MockService_CreateDefaultCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_CreateDefaultCategories_Call) Return(_a0 error) *MockService_CreateDefaultCategories_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CreateDefaultCategories_Call) RunAndReturn(run func(string) error) *MockService_CreateDefaultCategories_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: params
func (_m *MockService) Delete(params *model.CategorySearchParams) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.CategorySearchParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - params *model.CategorySearchParams
func (_e *MockService_Expecter) Delete(params interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", params)}
}

func (_c *MockService_Delete_Call) Run(run func(params *model.CategorySearchParams)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.CategorySearchParams))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(*model.CategorySearchParams) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function with given fields: userID
func (_m *MockService) GetAllByUserID(userID string) ([]entity.Category, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Category, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Category); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockService_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) GetAllByUserID(userID interface{}) *MockService_GetAllByUserID_Call {
	return &MockService_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", userID)}
}

func (_c *MockService_GetAllByUserID_Call) Run(run func(userID string)) *MockService_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_GetAllByUserID_Call) Return(_a0 []entity.Category, _a1 error) *MockService_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAllByUserID_Call) RunAndReturn(run func(string) ([]entity.Category, error)) *MockService_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserIDWithTransactions provides a mock function with given fields: userID, filter
func (_m *MockService) GetAllByUserIDWithTransactions(userID string, filter *model.TransactionFilter) ([]entity.Category, error) {
	ret := _m.Called(userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserIDWithTransactions")
	}

	var r0 []entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) ([]entity.Category, error)); ok {
		return rf(userID, filter)
	}
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) []entity.Category); ok {
		r0 = rf(userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.TransactionFilter) error); ok {
		r1 = rf(userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAllByUserIDWithTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserIDWithTransactions'
type MockService_GetAllByUserIDWithTransactions_Call struct {
	*mock.Call
}

// GetAllByUserIDWithTransactions is a helper method to define mock.On call
//   - userID string
//   - filter *model.TransactionFilter
func (_e *MockService_Expecter) GetAllByUserIDWithTransactions(userID interface{}, filter interface{}) *MockService_GetAllByUserIDWithTransactions_Call {
	return &MockService_GetAllByUserIDWithTransactions_Call{Call: _e.mock.On("GetAllByUserIDWithTransactions", userID, filter)}
}

func (_c *MockService_GetAllByUserIDWithTransactions_Call) Run(run func(userID string, filter *model.TransactionFilter)) *MockService_GetAllByUserIDWithTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.TransactionFilter))
	})
	return _c
}

func (_c *MockService_GetAllByUserIDWithTransactions_Call) Return(_a0 []entity.Category, _a1 error) *MockService_GetAllByUserIDWithTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAllByUserIDWithTransactions_Call) RunAndReturn(run func(string, *model.TransactionFilter) ([]entity.Category, error)) *MockService_GetAllByUserIDWithTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: params
func (_m *MockService) GetByID(params *model.CategorySearchParams) (*entity.Category, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.CategorySearchParams) (*entity.Category, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*model.CategorySearchParams) *entity.Category); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.CategorySearchParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - params *model.CategorySearchParams
func (_e *MockService_Expecter) GetByID(params interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", params)}
}

func (_c *MockService_GetByID_Call) Run(run func(params *model.CategorySearchParams)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.CategorySearchParams))
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(_a0 *entity.Category, _a1 error) *MockService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(*model.CategorySearchParams) (*entity.Category, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithTransactions provides a mock function with given fields: params, filter
func (_m *MockService) GetByIDWithTransactions(params *model.CategorySearchParams, filter *model.TransactionFilter) (*entity.Category, error) {
	ret := _m.Called(params, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithTransactions")
	}

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.CategorySearchParams, *model.TransactionFilter) (*entity.Category, error)); ok {
		return rf(params, filter)
	}
	if rf, ok := ret.Get(0).(func(*model.CategorySearchParams, *model.TransactionFilter) *entity.Category); ok {
		r0 = rf(params, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.CategorySearchParams, *model.TransactionFilter) error); ok {
		r1 = rf(params, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByIDWithTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithTransactions'
type MockService_GetByIDWithTransactions_Call struct {
	*mock.Call
}

// GetByIDWithTransactions is a helper method to define mock.On call
//   - params *model.CategorySearchParams
//   - filter *model.TransactionFilter
func (_e *MockService_Expecter) GetByIDWithTransactions(params interface{}, filter interface{}) *MockService_GetByIDWithTransactions_Call {
	return &MockService_GetByIDWithTransactions_Call{Call: _e.mock.On("GetByIDWithTransactions", params, filter)}
}

func (_c *MockService_GetByIDWithTransactions_Call) Run(run func(params *model.CategorySearchParams, filter *model.TransactionFilter)) *MockService_GetByIDWithTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.CategorySearchParams), args[1].(*model.TransactionFilter))
	})
	return _c
}

func (_c *MockService_GetByIDWithTransactions_Call) Return(_a0 *entity.Category, _a1 error) *MockService_GetByIDWithTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByIDWithTransactions_Call) RunAndReturn(run func(*model.CategorySearchParams, *model.TransactionFilter) (*entity.Category, error)) *MockService_GetByIDWithTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: params, input
func (_m *MockService) Update(params *model.CategorySearchParams, input *categorysvc.CategoryUpdateInput) (*entity.Category, error) {
	ret := _m.Called(params, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.CategorySearchParams, *categorysvc.CategoryUpdateInput) (*entity.Category, error)); ok {
		return rf(params, input)
	}
	if rf, ok := ret.Get(0).(func(*model.CategorySearchParams, *categorysvc.CategoryUpdateInput) *entity.Category); ok {
		r0 = rf(params, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.CategorySearchParams, *categorysvc.CategoryUpdateInput) error); ok {
		r1 = rf(params, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - params *model.CategorySearchParams
//   - input *categorysvc.CategoryUpdateInput
func (_e *MockService_Expecter) Update(params interface{}, input interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", params, input)}
}

func (_c *MockService_Update_Call) Run(run func(params *model.CategorySearchParams, input *categorysvc.CategoryUpdateInput)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.CategorySearchParams), args[1].(*categorysvc.CategoryUpdateInput))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *entity.Category, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(*model.CategorySearchParams, *categorysvc.CategoryUpdateInput) (*entity.Category, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
