// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	service "github.com/cp25sy5-modjot/main-service/internal/summary/service"

	time "time"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetCategorySummary provides a mock function with given fields: ctx, userID, period, date
func (_m *MockService) GetCategorySummary(ctx context.Context, userID string, period service.Period, date *time.Time) (model.CategorySummaryRes, error) {
	ret := _m.Called(ctx, userID, period, date)

	if len(ret) == 0 {
		panic("no return value specified for GetCategorySummary")
	}

	var r0 model.CategorySummaryRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.Period, *time.Time) (model.CategorySummaryRes, error)); ok {
		return rf(ctx, userID, period, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, service.Period, *time.Time) model.CategorySummaryRes); ok {
		r0 = rf(ctx, userID, period, date)
	} else {
		r0 = ret.Get(0).(model.CategorySummaryRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, service.Period, *time.Time) error); ok {
		r1 = rf(ctx, userID, period, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetCategorySummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategorySummary'
type MockService_GetCategorySummary_Call struct {
	*mock.Call
}

// GetCategorySummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - period service.Period
//   - date *time.Time
func (_e *MockService_Expecter) GetCategorySummary(ctx interface{}, userID interface{}, period interface{}, date interface{}) *MockService_GetCategorySummary_Call {
	return &MockService_GetCategorySummary_Call{Call: _e.mock.On("GetCategorySummary", ctx, userID, period, date)}
}

func (_c *MockService_GetCategorySummary_Call) Run(run func(ctx context.Context, userID string, period service.Period, date *time.Time)) *MockService_GetCategorySummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(service.Period), args[3].(*time.Time))
	})
	return _c
}

func (_c *MockService_GetCategorySummary_Call) Return(_a0 model.CategorySummaryRes, _a1 error) *MockService_GetCategorySummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetCategorySummary_Call) RunAndReturn(run func(context.Context, string, service.Period, *time.Time) (model.CategorySummaryRes, error)) *MockService_GetCategorySummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpenseSummary provides a mock function with given fields: ctx, userID, period
func (_m *MockService) GetExpenseSummary(ctx context.Context, userID string, period service.Period) (model.ExpenseSummaryRes, error) {
	ret := _m.Called(ctx, userID, period)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenseSummary")
	}

	var r0 model.ExpenseSummaryRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.Period) (model.ExpenseSummaryRes, error)); ok {
		return rf(ctx, userID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, service.Period) model.ExpenseSummaryRes); ok {
		r0 = rf(ctx, userID, period)
	} else {
		r0 = ret.Get(0).(model.ExpenseSummaryRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, service.Period) error); ok {
		r1 = rf(ctx, userID, period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetExpenseSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpenseSummary'
type MockService_GetExpenseSummary_Call struct {
	*mock.Call
}

// GetExpenseSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - period service.Period
func (_e *MockService_Expecter) GetExpenseSummary(ctx interface{}, userID interface{}, period interface{}) *MockService_GetExpenseSummary_Call {
	return &MockService_GetExpenseSummary_Call{Call: _e.mock.On("GetExpenseSummary", ctx, userID, period)}
}

func (_c *MockService_GetExpenseSummary_Call) Run(run func(ctx context.Context, userID string, period service.Period)) *MockService_GetExpenseSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(service.Period))
	})
	return _c
}

func (_c *MockService_GetExpenseSummary_Call) Return(_a0 model.ExpenseSummaryRes, _a1 error) *MockService_GetExpenseSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetExpenseSummary_Call) RunAndReturn(run func(context.Context, string, service.Period) (model.ExpenseSummaryRes, error)) *MockService_GetExpenseSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
