// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/cp25sy5-modjot/main-service/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: input
func (_m *MockService) Create(input *model.UserCreateInput) (*entity.User, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserCreateInput) (*entity.User, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*model.UserCreateInput) *entity.User); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserCreateInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - input *model.UserCreateInput
func (_e *MockService_Expecter) Create(input interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", input)}
}

func (_c *MockService_Create_Call) Run(run func(input *model.UserCreateInput)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.UserCreateInput))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *entity.User, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(*model.UserCreateInput) (*entity.User, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMockUser provides a mock function with given fields: input, uid
func (_m *MockService) CreateMockUser(input *model.UserCreateInput, uid string) (*entity.User, error) {
	ret := _m.Called(input, uid)

	if len(ret) == 0 {
		panic("no return value specified for CreateMockUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserCreateInput, string) (*entity.User, error)); ok {
		return rf(input, uid)
	}
	if rf, ok := ret.Get(0).(func(*model.UserCreateInput, string) *entity.User); ok {
		r0 = rf(input, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserCreateInput, string) error); ok {
		r1 = rf(input, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateMockUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMockUser'
type MockService_CreateMockUser_Call struct {
	*mock.Call
}

// CreateMockUser is a helper method to define mock.On call
//   - input *model.UserCreateInput
//   - uid string
func (_e *MockService_Expecter) CreateMockUser(input interface{}, uid interface{}) *MockService_CreateMockUser_Call {
	return &MockService_CreateMockUser_Call{Call: _e.mock.On("CreateMockUser", input, uid)}
}

func (_c *MockService_CreateMockUser_Call) Run(run func(input *model.UserCreateInput, uid string)) *MockService_CreateMockUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.UserCreateInput), args[1].(string))
	})
	return _c
}

func (_c *MockService_CreateMockUser_Call) Return(_a0 *entity.User, _a1 error) *MockService_CreateMockUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateMockUser_Call) RunAndReturn(run func(*model.UserCreateInput, string) (*entity.User, error)) *MockService_CreateMockUser_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: userID
func (_m *MockService) Delete(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) Delete(userID interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", userID)}
}

func (_c *MockService_Delete_Call) Run(run func(userID string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(string) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockService) GetAll() ([]*entity.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entity.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entity.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockService_Expecter) GetAll() *MockService_GetAll_Call {
	return &MockService_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockService_GetAll_Call) Run(run func()) *MockService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetAll_Call) Return(_a0 []*entity.User, _a1 error) *MockService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAll_Call) RunAndReturn(run func() ([]*entity.User, error)) *MockService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGoogleID provides a mock function with given fields: google_id
func (_m *MockService) GetByGoogleID(google_id string) (*entity.User, error) {
	ret := _m.Called(google_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByGoogleID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(google_id)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(google_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(google_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByGoogleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGoogleID'
type MockService_GetByGoogleID_Call struct {
	*mock.Call
}

// GetByGoogleID is a helper method to define mock.On call
//   - google_id string
func (_e *MockService_Expecter) GetByGoogleID(google_id interface{}) *MockService_GetByGoogleID_Call {
	return &MockService_GetByGoogleID_Call{Call: _e.mock.On("GetByGoogleID", google_id)}
}

func (_c *MockService_GetByGoogleID_Call) Run(run func(google_id string)) *MockService_GetByGoogleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_GetByGoogleID_Call) Return(_a0 *entity.User, _a1 error) *MockService_GetByGoogleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByGoogleID_Call) RunAndReturn(run func(string) (*entity.User, error)) *MockService_GetByGoogleID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: userID
func (_m *MockService) GetByID(userID string) (*entity.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) GetByID(userID interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", userID)}
}

func (_c *MockService_GetByID_Call) Run(run func(userID string)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(_a0 *entity.User, _a1 error) *MockService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(string) (*entity.User, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreByGoogleID provides a mock function with given fields: googleID
func (_m *MockService) RestoreByGoogleID(googleID string) (*entity.User, error) {
	ret := _m.Called(googleID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByGoogleID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(googleID)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(googleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(googleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RestoreByGoogleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreByGoogleID'
type MockService_RestoreByGoogleID_Call struct {
	*mock.Call
}

// RestoreByGoogleID is a helper method to define mock.On call
//   - googleID string
func (_e *MockService_Expecter) RestoreByGoogleID(googleID interface{}) *MockService_RestoreByGoogleID_Call {
	return &MockService_RestoreByGoogleID_Call{Call: _e.mock.On("RestoreByGoogleID", googleID)}
}

func (_c *MockService_RestoreByGoogleID_Call) Run(run func(googleID string)) *MockService_RestoreByGoogleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_RestoreByGoogleID_Call) Return(_a0 *entity.User, _a1 error) *MockService_RestoreByGoogleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RestoreByGoogleID_Call) RunAndReturn(run func(string) (*entity.User, error)) *MockService_RestoreByGoogleID_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreByUserID provides a mock function with given fields: userID
func (_m *MockService) RestoreByUserID(userID string) (*entity.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByUserID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RestoreByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreByUserID'
type MockService_RestoreByUserID_Call struct {
	*mock.Call
}

// RestoreByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) RestoreByUserID(userID interface{}) *MockService_RestoreByUserID_Call {
	return &MockService_RestoreByUserID_Call{Call: _e.mock.On("RestoreByUserID", userID)}
}

func (_c *MockService_RestoreByUserID_Call) Run(run func(userID string)) *MockService_RestoreByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_RestoreByUserID_Call) Return(_a0 *entity.User, _a1 error) *MockService_RestoreByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RestoreByUserID_Call) RunAndReturn(run func(string) (*entity.User, error)) *MockService_RestoreByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: userID
func (_m *MockService) SoftDelete(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockService_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) SoftDelete(userID interface{}) *MockService_SoftDelete_Call {
	return &MockService_SoftDelete_Call{Call: _e.mock.On("SoftDelete", userID)}
}

func (_c *MockService_SoftDelete_Call) Run(run func(userID string)) *MockService_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_SoftDelete_Call) Return(_a0 error) *MockService_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_SoftDelete_Call) RunAndReturn(run func(string) error) *MockService_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// TestSoftDelete provides a mock function with given fields: userID
func (_m *MockService) TestSoftDelete(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for TestSoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_TestSoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestSoftDelete'
type MockService_TestSoftDelete_Call struct {
	*mock.Call
}

// TestSoftDelete is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) TestSoftDelete(userID interface{}) *MockService_TestSoftDelete_Call {
	return &MockService_TestSoftDelete_Call{Call: _e.mock.On("TestSoftDelete", userID)}
}

func (_c *MockService_TestSoftDelete_Call) Run(run func(userID string)) *MockService_TestSoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_TestSoftDelete_Call) Return(_a0 error) *MockService_TestSoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_TestSoftDelete_Call) RunAndReturn(run func(string) error) *MockService_TestSoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: userID, input
func (_m *MockService) Update(userID string, input *model.UserUpdateInput) (*entity.User, error) {
	ret := _m.Called(userID, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.UserUpdateInput) (*entity.User, error)); ok {
		return rf(userID, input)
	}
	if rf, ok := ret.Get(0).(func(string, *model.UserUpdateInput) *entity.User); ok {
		r0 = rf(userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.UserUpdateInput) error); ok {
		r1 = rf(userID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID string
//   - input *model.UserUpdateInput
func (_e *MockService_Expecter) Update(userID interface{}, input interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", userID, input)}
}

func (_c *MockService_Update_Call) Run(run func(userID string, input *model.UserUpdateInput)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.UserUpdateInput))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *entity.User, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(string, *model.UserUpdateInput) (*entity.User, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
