// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/cp25sy5-modjot/main-service/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *Service) Create(input *model.UserCreateInput) (*entity.User, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserCreateInput) (*entity.User, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*model.UserCreateInput) *entity.User); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserCreateInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMockUser provides a mock function with given fields: input, uid
func (_m *Service) CreateMockUser(input *model.UserCreateInput, uid string) (*entity.User, error) {
	ret := _m.Called(input, uid)

	if len(ret) == 0 {
		panic("no return value specified for CreateMockUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserCreateInput, string) (*entity.User, error)); ok {
		return rf(input, uid)
	}
	if rf, ok := ret.Get(0).(func(*model.UserCreateInput, string) *entity.User); ok {
		r0 = rf(input, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserCreateInput, string) error); ok {
		r1 = rf(input, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: userID
func (_m *Service) Delete(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *Service) GetAll() ([]*entity.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entity.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entity.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByGoogleID provides a mock function with given fields: google_id
func (_m *Service) GetByGoogleID(google_id string) (*entity.User, error) {
	ret := _m.Called(google_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByGoogleID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(google_id)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(google_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(google_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: userID
func (_m *Service) GetByID(userID string) (*entity.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreByGoogleID provides a mock function with given fields: googleID
func (_m *Service) RestoreByGoogleID(googleID string) (*entity.User, error) {
	ret := _m.Called(googleID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByGoogleID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(googleID)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(googleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(googleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreByUserID provides a mock function with given fields: userID
func (_m *Service) RestoreByUserID(userID string) (*entity.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByUserID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: userID
func (_m *Service) SoftDelete(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TestSoftDelete provides a mock function with given fields: userID
func (_m *Service) TestSoftDelete(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for TestSoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: userID, input
func (_m *Service) Update(userID string, input *model.UserUpdateInput) (*entity.User, error) {
	ret := _m.Called(userID, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.UserUpdateInput) (*entity.User, error)); ok {
		return rf(userID, input)
	}
	if rf, ok := ret.Get(0).(func(string, *model.UserUpdateInput) *entity.User); ok {
		r0 = rf(userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.UserUpdateInput) error); ok {
		r1 = rf(userID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
