// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/cp25sy5-modjot/main-service/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"

	transactionsvc "github.com/cp25sy5-modjot/main-service/internal/transaction/service"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: userID, input
func (_m *MockService) Create(userID string, input *model.TransactionCreateInput) (*entity.Transaction, error) {
	ret := _m.Called(userID, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.TransactionCreateInput) (*entity.Transaction, error)); ok {
		return rf(userID, input)
	}
	if rf, ok := ret.Get(0).(func(string, *model.TransactionCreateInput) *entity.Transaction); ok {
		r0 = rf(userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.TransactionCreateInput) error); ok {
		r1 = rf(userID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userID string
//   - input *model.TransactionCreateInput
func (_e *MockService_Expecter) Create(userID interface{}, input interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", userID, input)}
}

func (_c *MockService_Create_Call) Run(run func(userID string, input *model.TransactionCreateInput)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.TransactionCreateInput))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *entity.Transaction, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(string, *model.TransactionCreateInput) (*entity.Transaction, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFromFixCost provides a mock function with given fields: ctx, fixCost
func (_m *MockService) CreateFromFixCost(ctx context.Context, fixCost *entity.FixCost) (*entity.Transaction, error) {
	ret := _m.Called(ctx, fixCost)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromFixCost")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.FixCost) (*entity.Transaction, error)); ok {
		return rf(ctx, fixCost)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.FixCost) *entity.Transaction); ok {
		r0 = rf(ctx, fixCost)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.FixCost) error); ok {
		r1 = rf(ctx, fixCost)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateFromFixCost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFromFixCost'
type MockService_CreateFromFixCost_Call struct {
	*mock.Call
}

// CreateFromFixCost is a helper method to define mock.On call
//   - ctx context.Context
//   - fixCost *entity.FixCost
func (_e *MockService_Expecter) CreateFromFixCost(ctx interface{}, fixCost interface{}) *MockService_CreateFromFixCost_Call {
	return &MockService_CreateFromFixCost_Call{Call: _e.mock.On("CreateFromFixCost", ctx, fixCost)}
}

func (_c *MockService_CreateFromFixCost_Call) Run(run func(ctx context.Context, fixCost *entity.FixCost)) *MockService_CreateFromFixCost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.FixCost))
	})
	return _c
}

func (_c *MockService_CreateFromFixCost_Call) Return(_a0 *entity.Transaction, _a1 error) *MockService_CreateFromFixCost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateFromFixCost_Call) RunAndReturn(run func(context.Context, *entity.FixCost) (*entity.Transaction, error)) *MockService_CreateFromFixCost_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: params
func (_m *MockService) Delete(params *model.TransactionSearchParams) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - params *model.TransactionSearchParams
func (_e *MockService_Expecter) Delete(params interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", params)}
}

func (_c *MockService_Delete_Call) Run(run func(params *model.TransactionSearchParams)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TransactionSearchParams))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(*model.TransactionSearchParams) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function with given fields: userID
func (_m *MockService) GetAllByUserID(userID string) ([]entity.Transaction, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Transaction, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Transaction); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockService_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) GetAllByUserID(userID interface{}) *MockService_GetAllByUserID_Call {
	return &MockService_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", userID)}
}

func (_c *MockService_GetAllByUserID_Call) Run(run func(userID string)) *MockService_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_GetAllByUserID_Call) Return(_a0 []entity.Transaction, _a1 error) *MockService_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAllByUserID_Call) RunAndReturn(run func(string) ([]entity.Transaction, error)) *MockService_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserIDWithFilter provides a mock function with given fields: userID, filter
func (_m *MockService) GetAllByUserIDWithFilter(userID string, filter *model.TransactionFilter) ([]entity.Transaction, error) {
	ret := _m.Called(userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserIDWithFilter")
	}

	var r0 []entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) ([]entity.Transaction, error)); ok {
		return rf(userID, filter)
	}
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) []entity.Transaction); ok {
		r0 = rf(userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.TransactionFilter) error); ok {
		r1 = rf(userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAllByUserIDWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserIDWithFilter'
type MockService_GetAllByUserIDWithFilter_Call struct {
	*mock.Call
}

// GetAllByUserIDWithFilter is a helper method to define mock.On call
//   - userID string
//   - filter *model.TransactionFilter
func (_e *MockService_Expecter) GetAllByUserIDWithFilter(userID interface{}, filter interface{}) *MockService_GetAllByUserIDWithFilter_Call {
	return &MockService_GetAllByUserIDWithFilter_Call{Call: _e.mock.On("GetAllByUserIDWithFilter", userID, filter)}
}

func (_c *MockService_GetAllByUserIDWithFilter_Call) Run(run func(userID string, filter *model.TransactionFilter)) *MockService_GetAllByUserIDWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.TransactionFilter))
	})
	return _c
}

func (_c *MockService_GetAllByUserIDWithFilter_Call) Return(_a0 []entity.Transaction, _a1 error) *MockService_GetAllByUserIDWithFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAllByUserIDWithFilter_Call) RunAndReturn(run func(string, *model.TransactionFilter) ([]entity.Transaction, error)) *MockService_GetAllByUserIDWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllComparePreviousMonthAndByUserIDWithFilter provides a mock function with given fields: userID, filter
func (_m *MockService) GetAllComparePreviousMonthAndByUserIDWithFilter(userID string, filter *model.TransactionFilter) (*transactionsvc.MonthlyResult, error) {
	ret := _m.Called(userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllComparePreviousMonthAndByUserIDWithFilter")
	}

	var r0 *transactionsvc.MonthlyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) (*transactionsvc.MonthlyResult, error)); ok {
		return rf(userID, filter)
	}
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) *transactionsvc.MonthlyResult); ok {
		r0 = rf(userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transactionsvc.MonthlyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.TransactionFilter) error); ok {
		r1 = rf(userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllComparePreviousMonthAndByUserIDWithFilter'
type MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call struct {
	*mock.Call
}

// GetAllComparePreviousMonthAndByUserIDWithFilter is a helper method to define mock.On call
//   - userID string
//   - filter *model.TransactionFilter
func (_e *MockService_Expecter) GetAllComparePreviousMonthAndByUserIDWithFilter(userID interface{}, filter interface{}) *MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call {
	return &MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call{Call: _e.mock.On("GetAllComparePreviousMonthAndByUserIDWithFilter", userID, filter)}
}

func (_c *MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call) Run(run func(userID string, filter *model.TransactionFilter)) *MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.TransactionFilter))
	})
	return _c
}

func (_c *MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call) Return(_a0 *transactionsvc.MonthlyResult, _a1 error) *MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call) RunAndReturn(run func(string, *model.TransactionFilter) (*transactionsvc.MonthlyResult, error)) *MockService_GetAllComparePreviousMonthAndByUserIDWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: params
func (_m *MockService) GetByID(params *model.TransactionSearchParams) (*entity.Transaction, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams) (*entity.Transaction, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams) *entity.Transaction); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.TransactionSearchParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - params *model.TransactionSearchParams
func (_e *MockService_Expecter) GetByID(params interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", params)}
}

func (_c *MockService_GetByID_Call) Run(run func(params *model.TransactionSearchParams)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TransactionSearchParams))
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(_a0 *entity.Transaction, _a1 error) *MockService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(*model.TransactionSearchParams) (*entity.Transaction, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessUploadedFile provides a mock function with given fields: fileData, userID
func (_m *MockService) ProcessUploadedFile(fileData []byte, userID string) (*model.DraftTxn, error) {
	ret := _m.Called(fileData, userID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessUploadedFile")
	}

	var r0 *model.DraftTxn
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string) (*model.DraftTxn, error)); ok {
		return rf(fileData, userID)
	}
	if rf, ok := ret.Get(0).(func([]byte, string) *model.DraftTxn); ok {
		r0 = rf(fileData, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DraftTxn)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = rf(fileData, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ProcessUploadedFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessUploadedFile'
type MockService_ProcessUploadedFile_Call struct {
	*mock.Call
}

// ProcessUploadedFile is a helper method to define mock.On call
//   - fileData []byte
//   - userID string
func (_e *MockService_Expecter) ProcessUploadedFile(fileData interface{}, userID interface{}) *MockService_ProcessUploadedFile_Call {
	return &MockService_ProcessUploadedFile_Call{Call: _e.mock.On("ProcessUploadedFile", fileData, userID)}
}

func (_c *MockService_ProcessUploadedFile_Call) Run(run func(fileData []byte, userID string)) *MockService_ProcessUploadedFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(string))
	})
	return _c
}

func (_c *MockService_ProcessUploadedFile_Call) Return(_a0 *model.DraftTxn, _a1 error) *MockService_ProcessUploadedFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ProcessUploadedFile_Call) RunAndReturn(run func([]byte, string) (*model.DraftTxn, error)) *MockService_ProcessUploadedFile_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: params, input
func (_m *MockService) Update(params *model.TransactionSearchParams, input *model.TransactionUpdateInput) (*entity.Transaction, error) {
	ret := _m.Called(params, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams, *model.TransactionUpdateInput) (*entity.Transaction, error)); ok {
		return rf(params, input)
	}
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams, *model.TransactionUpdateInput) *entity.Transaction); ok {
		r0 = rf(params, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.TransactionSearchParams, *model.TransactionUpdateInput) error); ok {
		r1 = rf(params, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - params *model.TransactionSearchParams
//   - input *model.TransactionUpdateInput
func (_e *MockService_Expecter) Update(params interface{}, input interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", params, input)}
}

func (_c *MockService_Update_Call) Run(run func(params *model.TransactionSearchParams, input *model.TransactionUpdateInput)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TransactionSearchParams), args[1].(*model.TransactionUpdateInput))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *entity.Transaction, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(*model.TransactionSearchParams, *model.TransactionUpdateInput) (*entity.Transaction, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
