// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/cp25sy5-modjot/main-service/internal/domain/entity"
	draft "github.com/cp25sy5-modjot/main-service/internal/draft"

	mock "github.com/stretchr/testify/mock"

	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"

	transactionsvc "github.com/cp25sy5-modjot/main-service/internal/transaction/service"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: userID, input
func (_m *Service) Create(userID string, input *model.TransactionCreateInput) (*entity.Transaction, error) {
	ret := _m.Called(userID, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.TransactionCreateInput) (*entity.Transaction, error)); ok {
		return rf(userID, input)
	}
	if rf, ok := ret.Get(0).(func(string, *model.TransactionCreateInput) *entity.Transaction); ok {
		r0 = rf(userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.TransactionCreateInput) error); ok {
		r1 = rf(userID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateFromFixCost provides a mock function with given fields: ctx, fixCost
func (_m *Service) CreateFromFixCost(ctx context.Context, fixCost *entity.FixCost) (*entity.Transaction, error) {
	ret := _m.Called(ctx, fixCost)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromFixCost")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.FixCost) (*entity.Transaction, error)); ok {
		return rf(ctx, fixCost)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.FixCost) *entity.Transaction); ok {
		r0 = rf(ctx, fixCost)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.FixCost) error); ok {
		r1 = rf(ctx, fixCost)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: params
func (_m *Service) Delete(params *model.TransactionSearchParams) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllByUserID provides a mock function with given fields: userID
func (_m *Service) GetAllByUserID(userID string) ([]entity.Transaction, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Transaction, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Transaction); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByUserIDWithFilter provides a mock function with given fields: userID, filter
func (_m *Service) GetAllByUserIDWithFilter(userID string, filter *model.TransactionFilter) ([]entity.Transaction, error) {
	ret := _m.Called(userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserIDWithFilter")
	}

	var r0 []entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) ([]entity.Transaction, error)); ok {
		return rf(userID, filter)
	}
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) []entity.Transaction); ok {
		r0 = rf(userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.TransactionFilter) error); ok {
		r1 = rf(userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllComparePreviousMonthAndByUserIDWithFilter provides a mock function with given fields: userID, filter
func (_m *Service) GetAllComparePreviousMonthAndByUserIDWithFilter(userID string, filter *model.TransactionFilter) (*transactionsvc.MonthlyResult, error) {
	ret := _m.Called(userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllComparePreviousMonthAndByUserIDWithFilter")
	}

	var r0 *transactionsvc.MonthlyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) (*transactionsvc.MonthlyResult, error)); ok {
		return rf(userID, filter)
	}
	if rf, ok := ret.Get(0).(func(string, *model.TransactionFilter) *transactionsvc.MonthlyResult); ok {
		r0 = rf(userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transactionsvc.MonthlyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *model.TransactionFilter) error); ok {
		r1 = rf(userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: params
func (_m *Service) GetByID(params *model.TransactionSearchParams) (*entity.Transaction, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams) (*entity.Transaction, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams) *entity.Transaction); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.TransactionSearchParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessUploadedFile provides a mock function with given fields: fileData, userID
func (_m *Service) ProcessUploadedFile(fileData []byte, userID string) (*draft.DraftTxn, error) {
	ret := _m.Called(fileData, userID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessUploadedFile")
	}

	var r0 *draft.DraftTxn
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string) (*draft.DraftTxn, error)); ok {
		return rf(fileData, userID)
	}
	if rf, ok := ret.Get(0).(func([]byte, string) *draft.DraftTxn); ok {
		r0 = rf(fileData, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*draft.DraftTxn)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = rf(fileData, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: params, input
func (_m *Service) Update(params *model.TransactionSearchParams, input *model.TransactionUpdateInput) (*entity.Transaction, error) {
	ret := _m.Called(params, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams, *model.TransactionUpdateInput) (*entity.Transaction, error)); ok {
		return rf(params, input)
	}
	if rf, ok := ret.Get(0).(func(*model.TransactionSearchParams, *model.TransactionUpdateInput) *entity.Transaction); ok {
		r0 = rf(params, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.TransactionSearchParams, *model.TransactionUpdateInput) error); ok {
		r1 = rf(params, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
