// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/cp25sy5-modjot/main-service/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"

	txisvc "github.com/cp25sy5-modjot/main-service/internal/transaction_item/service"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: params
func (_m *MockService) Delete(params *model.TransactionItemSearchParams) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.TransactionItemSearchParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - params *model.TransactionItemSearchParams
func (_e *MockService_Expecter) Delete(params interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", params)}
}

func (_c *MockService_Delete_Call) Run(run func(params *model.TransactionItemSearchParams)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TransactionItemSearchParams))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(*model.TransactionItemSearchParams) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function with given fields: userID
func (_m *MockService) GetAllByUserID(userID string) ([]entity.TransactionItem, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []entity.TransactionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.TransactionItem, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.TransactionItem); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TransactionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockService_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) GetAllByUserID(userID interface{}) *MockService_GetAllByUserID_Call {
	return &MockService_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", userID)}
}

func (_c *MockService_GetAllByUserID_Call) Run(run func(userID string)) *MockService_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_GetAllByUserID_Call) Return(_a0 []entity.TransactionItem, _a1 error) *MockService_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAllByUserID_Call) RunAndReturn(run func(string) ([]entity.TransactionItem, error)) *MockService_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: params
func (_m *MockService) GetByID(params *model.TransactionItemSearchParams) (*entity.TransactionItem, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.TransactionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.TransactionItemSearchParams) (*entity.TransactionItem, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*model.TransactionItemSearchParams) *entity.TransactionItem); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TransactionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.TransactionItemSearchParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - params *model.TransactionItemSearchParams
func (_e *MockService_Expecter) GetByID(params interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", params)}
}

func (_c *MockService_GetByID_Call) Run(run func(params *model.TransactionItemSearchParams)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TransactionItemSearchParams))
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(_a0 *entity.TransactionItem, _a1 error) *MockService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(*model.TransactionItemSearchParams) (*entity.TransactionItem, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: params, input
func (_m *MockService) Update(params *model.TransactionItemSearchParams, input *txisvc.TransactionItemUpdateInput) (*entity.TransactionItem, error) {
	ret := _m.Called(params, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.TransactionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.TransactionItemSearchParams, *txisvc.TransactionItemUpdateInput) (*entity.TransactionItem, error)); ok {
		return rf(params, input)
	}
	if rf, ok := ret.Get(0).(func(*model.TransactionItemSearchParams, *txisvc.TransactionItemUpdateInput) *entity.TransactionItem); ok {
		r0 = rf(params, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TransactionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.TransactionItemSearchParams, *txisvc.TransactionItemUpdateInput) error); ok {
		r1 = rf(params, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - params *model.TransactionItemSearchParams
//   - input *txisvc.TransactionItemUpdateInput
func (_e *MockService_Expecter) Update(params interface{}, input interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", params, input)}
}

func (_c *MockService_Update_Call) Run(run func(params *model.TransactionItemSearchParams, input *txisvc.TransactionItemUpdateInput)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TransactionItemSearchParams), args[1].(*txisvc.TransactionItemUpdateInput))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *entity.TransactionItem, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(*model.TransactionItemSearchParams, *txisvc.TransactionItemUpdateInput) (*entity.TransactionItem, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
