// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/cp25sy5-modjot/main-service/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: input
func (_m *MockService) Create(input *model.FavoriteItemCreateInput) (*entity.FavoriteItem, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.FavoriteItem
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.FavoriteItemCreateInput) (*entity.FavoriteItem, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*model.FavoriteItemCreateInput) *entity.FavoriteItem); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.FavoriteItem)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.FavoriteItemCreateInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - input *model.FavoriteItemCreateInput
func (_e *MockService_Expecter) Create(input interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", input)}
}

func (_c *MockService_Create_Call) Run(run func(input *model.FavoriteItemCreateInput)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.FavoriteItemCreateInput))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *entity.FavoriteItem, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(*model.FavoriteItemCreateInput) (*entity.FavoriteItem, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: uid, fav_id
func (_m *MockService) Delete(uid string, fav_id string) error {
	ret := _m.Called(uid, fav_id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(uid, fav_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - uid string
//   - fav_id string
func (_e *MockService_Expecter) Delete(uid interface{}, fav_id interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", uid, fav_id)}
}

func (_c *MockService_Delete_Call) Run(run func(uid string, fav_id string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(string, string) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: uid
func (_m *MockService) GetAll(uid string) ([]*entity.FavoriteItem, error) {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.FavoriteItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*entity.FavoriteItem, error)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(string) []*entity.FavoriteItem); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.FavoriteItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - uid string
func (_e *MockService_Expecter) GetAll(uid interface{}) *MockService_GetAll_Call {
	return &MockService_GetAll_Call{Call: _e.mock.On("GetAll", uid)}
}

func (_c *MockService_GetAll_Call) Run(run func(uid string)) *MockService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_GetAll_Call) Return(_a0 []*entity.FavoriteItem, _a1 error) *MockService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAll_Call) RunAndReturn(run func(string) ([]*entity.FavoriteItem, error)) *MockService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: uid, fav_id
func (_m *MockService) GetByID(uid string, fav_id string) (*entity.FavoriteItem, error) {
	ret := _m.Called(uid, fav_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.FavoriteItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*entity.FavoriteItem, error)); ok {
		return rf(uid, fav_id)
	}
	if rf, ok := ret.Get(0).(func(string, string) *entity.FavoriteItem); ok {
		r0 = rf(uid, fav_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.FavoriteItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(uid, fav_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - uid string
//   - fav_id string
func (_e *MockService_Expecter) GetByID(uid interface{}, fav_id interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", uid, fav_id)}
}

func (_c *MockService_GetByID_Call) Run(run func(uid string, fav_id string)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(_a0 *entity.FavoriteItem, _a1 error) *MockService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(string, string) (*entity.FavoriteItem, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ReOrder provides a mock function with given fields: req
func (_m *MockService) ReOrder(req *model.FavoriteItemReOrderInput) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ReOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.FavoriteItemReOrderInput) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ReOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReOrder'
type MockService_ReOrder_Call struct {
	*mock.Call
}

// ReOrder is a helper method to define mock.On call
//   - req *model.FavoriteItemReOrderInput
func (_e *MockService_Expecter) ReOrder(req interface{}) *MockService_ReOrder_Call {
	return &MockService_ReOrder_Call{Call: _e.mock.On("ReOrder", req)}
}

func (_c *MockService_ReOrder_Call) Run(run func(req *model.FavoriteItemReOrderInput)) *MockService_ReOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.FavoriteItemReOrderInput))
	})
	return _c
}

func (_c *MockService_ReOrder_Call) Return(_a0 error) *MockService_ReOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ReOrder_Call) RunAndReturn(run func(*model.FavoriteItemReOrderInput) error) *MockService_ReOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: input
func (_m *MockService) Update(input *model.FavoriteItemUpdateInput) (*entity.FavoriteItem, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.FavoriteItem
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.FavoriteItemUpdateInput) (*entity.FavoriteItem, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*model.FavoriteItemUpdateInput) *entity.FavoriteItem); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.FavoriteItem)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.FavoriteItemUpdateInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - input *model.FavoriteItemUpdateInput
func (_e *MockService_Expecter) Update(input interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", input)}
}

func (_c *MockService_Update_Call) Run(run func(input *model.FavoriteItemUpdateInput)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.FavoriteItemUpdateInput))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *entity.FavoriteItem, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(*model.FavoriteItemUpdateInput) (*entity.FavoriteItem, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
