// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/cp25sy5-modjot/main-service/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ConfirmDraft provides a mock function with given fields: ctx, draftID, userID, req
func (_m *MockService) ConfirmDraft(ctx context.Context, draftID string, userID string, req model.ConfirmRequest) (*entity.Transaction, error) {
	ret := _m.Called(ctx, draftID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmDraft")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.ConfirmRequest) (*entity.Transaction, error)); ok {
		return rf(ctx, draftID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.ConfirmRequest) *entity.Transaction); ok {
		r0 = rf(ctx, draftID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.ConfirmRequest) error); ok {
		r1 = rf(ctx, draftID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ConfirmDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmDraft'
type MockService_ConfirmDraft_Call struct {
	*mock.Call
}

// ConfirmDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - draftID string
//   - userID string
//   - req model.ConfirmRequest
func (_e *MockService_Expecter) ConfirmDraft(ctx interface{}, draftID interface{}, userID interface{}, req interface{}) *MockService_ConfirmDraft_Call {
	return &MockService_ConfirmDraft_Call{Call: _e.mock.On("ConfirmDraft", ctx, draftID, userID, req)}
}

func (_c *MockService_ConfirmDraft_Call) Run(run func(ctx context.Context, draftID string, userID string, req model.ConfirmRequest)) *MockService_ConfirmDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.ConfirmRequest))
	})
	return _c
}

func (_c *MockService_ConfirmDraft_Call) Return(_a0 *entity.Transaction, _a1 error) *MockService_ConfirmDraft_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ConfirmDraft_Call) RunAndReturn(run func(context.Context, string, string, model.ConfirmRequest) (*entity.Transaction, error)) *MockService_ConfirmDraft_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDraft provides a mock function with given fields: ctx, draftID, userID
func (_m *MockService) DeleteDraft(ctx context.Context, draftID string, userID string) error {
	ret := _m.Called(ctx, draftID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDraft")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, draftID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDraft'
type MockService_DeleteDraft_Call struct {
	*mock.Call
}

// DeleteDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - draftID string
//   - userID string
func (_e *MockService_Expecter) DeleteDraft(ctx interface{}, draftID interface{}, userID interface{}) *MockService_DeleteDraft_Call {
	return &MockService_DeleteDraft_Call{Call: _e.mock.On("DeleteDraft", ctx, draftID, userID)}
}

func (_c *MockService_DeleteDraft_Call) Run(run func(ctx context.Context, draftID string, userID string)) *MockService_DeleteDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteDraft_Call) Return(_a0 error) *MockService_DeleteDraft_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteDraft_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteDraft_Call {
	_c.Call.Return(run)
	return _c
}

// GetDraftImageURL provides a mock function with given fields: ctx, draftID, userID
func (_m *MockService) GetDraftImageURL(ctx context.Context, draftID string, userID string) (string, error) {
	ret := _m.Called(ctx, draftID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDraftImageURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, draftID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, draftID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, draftID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDraftImageURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDraftImageURL'
type MockService_GetDraftImageURL_Call struct {
	*mock.Call
}

// GetDraftImageURL is a helper method to define mock.On call
//   - ctx context.Context
//   - draftID string
//   - userID string
func (_e *MockService_Expecter) GetDraftImageURL(ctx interface{}, draftID interface{}, userID interface{}) *MockService_GetDraftImageURL_Call {
	return &MockService_GetDraftImageURL_Call{Call: _e.mock.On("GetDraftImageURL", ctx, draftID, userID)}
}

func (_c *MockService_GetDraftImageURL_Call) Run(run func(ctx context.Context, draftID string, userID string)) *MockService_GetDraftImageURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetDraftImageURL_Call) Return(_a0 string, _a1 error) *MockService_GetDraftImageURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDraftImageURL_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockService_GetDraftImageURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetDraftStats provides a mock function with given fields: ctx, userID
func (_m *MockService) GetDraftStats(ctx context.Context, userID string) (*model.DraftStats, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDraftStats")
	}

	var r0 *model.DraftStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.DraftStats, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.DraftStats); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DraftStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDraftStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDraftStats'
type MockService_GetDraftStats_Call struct {
	*mock.Call
}

// GetDraftStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) GetDraftStats(ctx interface{}, userID interface{}) *MockService_GetDraftStats_Call {
	return &MockService_GetDraftStats_Call{Call: _e.mock.On("GetDraftStats", ctx, userID)}
}

func (_c *MockService_GetDraftStats_Call) Run(run func(ctx context.Context, userID string)) *MockService_GetDraftStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetDraftStats_Call) Return(_a0 *model.DraftStats, _a1 error) *MockService_GetDraftStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDraftStats_Call) RunAndReturn(run func(context.Context, string) (*model.DraftStats, error)) *MockService_GetDraftStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetDraftWithCategory provides a mock function with given fields: ctx, draftID, userID
func (_m *MockService) GetDraftWithCategory(ctx context.Context, draftID string, userID string) (*model.DraftRes, error) {
	ret := _m.Called(ctx, draftID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDraftWithCategory")
	}

	var r0 *model.DraftRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.DraftRes, error)); ok {
		return rf(ctx, draftID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.DraftRes); ok {
		r0 = rf(ctx, draftID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DraftRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, draftID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDraftWithCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDraftWithCategory'
type MockService_GetDraftWithCategory_Call struct {
	*mock.Call
}

// GetDraftWithCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - draftID string
//   - userID string
func (_e *MockService_Expecter) GetDraftWithCategory(ctx interface{}, draftID interface{}, userID interface{}) *MockService_GetDraftWithCategory_Call {
	return &MockService_GetDraftWithCategory_Call{Call: _e.mock.On("GetDraftWithCategory", ctx, draftID, userID)}
}

func (_c *MockService_GetDraftWithCategory_Call) Run(run func(ctx context.Context, draftID string, userID string)) *MockService_GetDraftWithCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetDraftWithCategory_Call) Return(_a0 *model.DraftRes, _a1 error) *MockService_GetDraftWithCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDraftWithCategory_Call) RunAndReturn(run func(context.Context, string, string) (*model.DraftRes, error)) *MockService_GetDraftWithCategory_Call {
	_c.Call.Return(run)
	return _c
}

// ListDraftWithCategory provides a mock function with given fields: ctx, userID
func (_m *MockService) ListDraftWithCategory(ctx context.Context, userID string) ([]model.DraftRes, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListDraftWithCategory")
	}

	var r0 []model.DraftRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.DraftRes, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.DraftRes); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DraftRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListDraftWithCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDraftWithCategory'
type MockService_ListDraftWithCategory_Call struct {
	*mock.Call
}

// ListDraftWithCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockService_Expecter) ListDraftWithCategory(ctx interface{}, userID interface{}) *MockService_ListDraftWithCategory_Call {
	return &MockService_ListDraftWithCategory_Call{Call: _e.mock.On("ListDraftWithCategory", ctx, userID)}
}

func (_c *MockService_ListDraftWithCategory_Call) Run(run func(ctx context.Context, userID string)) *MockService_ListDraftWithCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ListDraftWithCategory_Call) Return(_a0 []model.DraftRes, _a1 error) *MockService_ListDraftWithCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListDraftWithCategory_Call) RunAndReturn(run func(context.Context, string) ([]model.DraftRes, error)) *MockService_ListDraftWithCategory_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDraft provides a mock function with given fields: ctx, draftID, userID, req
func (_m *MockService) SaveDraft(ctx context.Context, draftID string, userID string, req model.NewDraftRequest) (*model.DraftTxn, error) {
	ret := _m.Called(ctx, draftID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for SaveDraft")
	}

	var r0 *model.DraftTxn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.NewDraftRequest) (*model.DraftTxn, error)); ok {
		return rf(ctx, draftID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.NewDraftRequest) *model.DraftTxn); ok {
		r0 = rf(ctx, draftID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DraftTxn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.NewDraftRequest) error); ok {
		r1 = rf(ctx, draftID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_SaveDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDraft'
type MockService_SaveDraft_Call struct {
	*mock.Call
}

// SaveDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - draftID string
//   - userID string
//   - req model.NewDraftRequest
func (_e *MockService_Expecter) SaveDraft(ctx interface{}, draftID interface{}, userID interface{}, req interface{}) *MockService_SaveDraft_Call {
	return &MockService_SaveDraft_Call{Call: _e.mock.On("SaveDraft", ctx, draftID, userID, req)}
}

func (_c *MockService_SaveDraft_Call) Run(run func(ctx context.Context, draftID string, userID string, req model.NewDraftRequest)) *MockService_SaveDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.NewDraftRequest))
	})
	return _c
}

func (_c *MockService_SaveDraft_Call) Return(_a0 *model.DraftTxn, _a1 error) *MockService_SaveDraft_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_SaveDraft_Call) RunAndReturn(run func(context.Context, string, string, model.NewDraftRequest) (*model.DraftTxn, error)) *MockService_SaveDraft_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDraft provides a mock function with given fields: ctx, draftID, userID, req
func (_m *MockService) UpdateDraft(ctx context.Context, draftID string, userID string, req model.ConfirmRequest) (*model.DraftTxn, error) {
	ret := _m.Called(ctx, draftID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDraft")
	}

	var r0 *model.DraftTxn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.ConfirmRequest) (*model.DraftTxn, error)); ok {
		return rf(ctx, draftID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.ConfirmRequest) *model.DraftTxn); ok {
		r0 = rf(ctx, draftID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DraftTxn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.ConfirmRequest) error); ok {
		r1 = rf(ctx, draftID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDraft'
type MockService_UpdateDraft_Call struct {
	*mock.Call
}

// UpdateDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - draftID string
//   - userID string
//   - req model.ConfirmRequest
func (_e *MockService_Expecter) UpdateDraft(ctx interface{}, draftID interface{}, userID interface{}, req interface{}) *MockService_UpdateDraft_Call {
	return &MockService_UpdateDraft_Call{Call: _e.mock.On("UpdateDraft", ctx, draftID, userID, req)}
}

func (_c *MockService_UpdateDraft_Call) Run(run func(ctx context.Context, draftID string, userID string, req model.ConfirmRequest)) *MockService_UpdateDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.ConfirmRequest))
	})
	return _c
}

func (_c *MockService_UpdateDraft_Call) Return(_a0 *model.DraftTxn, _a1 error) *MockService_UpdateDraft_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateDraft_Call) RunAndReturn(run func(context.Context, string, string, model.ConfirmRequest) (*model.DraftTxn, error)) *MockService_UpdateDraft_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
