// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/cp25sy5-modjot/main-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetOverview provides a mock function with given fields: userID, baseDate
func (_m *MockService) GetOverview(userID string, baseDate time.Time) (*model.OverviewResponse, error) {
	ret := _m.Called(userID, baseDate)

	if len(ret) == 0 {
		panic("no return value specified for GetOverview")
	}

	var r0 *model.OverviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time) (*model.OverviewResponse, error)); ok {
		return rf(userID, baseDate)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time) *model.OverviewResponse); ok {
		r0 = rf(userID, baseDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OverviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(userID, baseDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverview'
type MockService_GetOverview_Call struct {
	*mock.Call
}

// GetOverview is a helper method to define mock.On call
//   - userID string
//   - baseDate time.Time
func (_e *MockService_Expecter) GetOverview(userID interface{}, baseDate interface{}) *MockService_GetOverview_Call {
	return &MockService_GetOverview_Call{Call: _e.mock.On("GetOverview", userID, baseDate)}
}

func (_c *MockService_GetOverview_Call) Run(run func(userID string, baseDate time.Time)) *MockService_GetOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time))
	})
	return _c
}

func (_c *MockService_GetOverview_Call) Return(_a0 *model.OverviewResponse, _a1 error) *MockService_GetOverview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetOverview_Call) RunAndReturn(run func(string, time.Time) (*model.OverviewResponse, error)) *MockService_GetOverview_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
