// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, path
func (_m *MockStorage) Delete(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockStorage_Expecter) Delete(ctx interface{}, path interface{}) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, path string)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(_a0 error) *MockStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSignedURL provides a mock function with given fields: path, expiry, secret
func (_m *MockStorage) GenerateSignedURL(path string, expiry time.Duration, secret string) string {
	ret := _m.Called(path, expiry, secret)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSignedURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, time.Duration, string) string); ok {
		r0 = rf(path, expiry, secret)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStorage_GenerateSignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSignedURL'
type MockStorage_GenerateSignedURL_Call struct {
	*mock.Call
}

// GenerateSignedURL is a helper method to define mock.On call
//   - path string
//   - expiry time.Duration
//   - secret string
func (_e *MockStorage_Expecter) GenerateSignedURL(path interface{}, expiry interface{}, secret interface{}) *MockStorage_GenerateSignedURL_Call {
	return &MockStorage_GenerateSignedURL_Call{Call: _e.mock.On("GenerateSignedURL", path, expiry, secret)}
}

func (_c *MockStorage_GenerateSignedURL_Call) Run(run func(path string, expiry time.Duration, secret string)) *MockStorage_GenerateSignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_GenerateSignedURL_Call) Return(_a0 string) *MockStorage_GenerateSignedURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_GenerateSignedURL_Call) RunAndReturn(run func(string, time.Duration, string) string) *MockStorage_GenerateSignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: ctx, path
func (_m *MockStorage) Load(ctx context.Context, path string) ([]byte, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockStorage_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockStorage_Expecter) Load(ctx interface{}, path interface{}) *MockStorage_Load_Call {
	return &MockStorage_Load_Call{Call: _e.mock.On("Load", ctx, path)}
}

func (_c *MockStorage_Load_Call) Run(run func(ctx context.Context, path string)) *MockStorage_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Load_Call) Return(_a0 []byte, _a1 error) *MockStorage_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Load_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockStorage_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, userID, fileName, data, ext
func (_m *MockStorage) Save(ctx context.Context, userID string, fileName string, data []byte, ext string) (string, error) {
	ret := _m.Called(ctx, userID, fileName, data, ext)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, string) (string, error)); ok {
		return rf(ctx, userID, fileName, data, ext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, string) string); ok {
		r0 = rf(ctx, userID, fileName, data, ext)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte, string) error); ok {
		r1 = rf(ctx, userID, fileName, data, ext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - fileName string
//   - data []byte
//   - ext string
func (_e *MockStorage_Expecter) Save(ctx interface{}, userID interface{}, fileName interface{}, data interface{}, ext interface{}) *MockStorage_Save_Call {
	return &MockStorage_Save_Call{Call: _e.mock.On("Save", ctx, userID, fileName, data, ext)}
}

func (_c *MockStorage_Save_Call) Run(run func(ctx context.Context, userID string, fileName string, data []byte, ext string)) *MockStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte), args[4].(string))
	})
	return _c
}

func (_c *MockStorage_Save_Call) Return(_a0 string, _a1 error) *MockStorage_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Save_Call) RunAndReturn(run func(context.Context, string, string, []byte, string) (string, error)) *MockStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
